---
title: Troubleshooting
---

# Troubleshooting

## Accounts

### "I Can't Sign In / Up!"

If this is the first time you're signing in to your production Nodem instance, you'll need to set up an owner account via CLI. Refer to the [Owner Account Setup](/docs/nodem/usage/owner) page for additional information and guidance.

If you're attempting to sign up after receiving an invitation code, make sure that you're entering your username and invite code exactly as generated by your team's Owner or Admin. Refer to the [Team Sign Up](/docs/nodem/usage/teams#signing-up) section for additional information and guidance.

## Servers

### "My Server Isn't Importing!"

This is typically because of a failed connection or attempt to import a duplicate server, visit [Server Import Errors](/docs/nodem/usage/servers#import-errors) section for additional information and guidance.

---

If you find a bug or issue while installing or using Nodem, you can create an issue or contribute a fix by opening a pull request in Nodem's official open-source repo on GitHub.

<livewire:embed-link url="https://github.com/ArkEcosystem/nodem4979caac887a" caption="Official Nodem Repo" />
