---
title: Usage - Team Management
---

# Team Management

With Nodem, you can work collaboratively by inviting team members and setting access roles from a simple and intuitive interface. Managing your Core Servers has never been easier!

![](/storage/docs/docs/nodem/assets/usage/teams-dashboard.png)

This page will serve as your guide to the process of managing and maintaining your Nodem team and will provide important information along the way.

Owner accounts and Team Admins may:

* [invite](#inviting-team-members) team members,
* [remove](#canceling-an-invite) pending invitations,
* [edit](#editing-team-members) existing team members, or
* [remove](#removing-team-members) team members.

Additionally, new team members must [sign-up](#signing-up) using their unique invitation code generated by an owner or admin.

## Inviting Team Members

Owner accounts and Team Admins can add additional team member accounts using a basic create-and-share scheme--i.e., an owner or admin creates an invitation code that others use to sign up and gain access to the Nodem deployment.

### 1) Navigate to the Team Management Dashboard

Start by clicking on your profile's avatar, then select **'team'** from the dropdown menu.

![](/storage/docs/docs/nodem/assets/usage/teams-menu-select.png)

### 2) Click 'Invite'

Click the **'Invite'** button on the Team Management Dashboard.

![](/storage/docs/docs/nodem/assets/usage/teams-invite-button.png)

### 3) Enter the Member's Details

Enter the details of the person you want to invite.

![](/storage/docs/docs/nodem/assets/usage/teams-invite-details.png)

* **Username** - This will be used by your new team member at sign-up and to sign-in to Nodem
  * It must:
    * be at least 3 characters in length;
    * contain only letters, numbers, and underscores (_); and
    * _not_ begin or end with a special character.
  * It will be visible in the Team Management Dashboard
  * It cannot be changed. If a new username is desired, the team member account must be removed, and a new account must be created
* **Roles** - Assignable permissions that decide which actions may be performed by a team member
  * Only a team's owner or a team admin can modify roles
  * **Readonly**
    * Permitted to view servers and team members
    * Permitted to change their password or configure 2FA
    * May _not_ perform server actions (e.g., start, stop, add, remove, etc.)
    * May _not_ add, edit, or remove team members
  * **Maintainer**
    * All 'Readonly' permissions
    * Permitted to perform only basic server actions (e.g., start, stop, restart, etc.)
  * **Admin**
    * All 'Maintainer' permissions
    * Permitted to perform all server actions, including the import, export, and addition of servers.
    * Permitted to add, edit, or remove team members, including the reassignment of roles

### 4) Generate an Invitation Code

Click 'Generate' to create your new member's invitation code.

![](/storage/docs/docs/nodem/assets/usage/teams-invite-generate.png)

### 5) Share the Invitation Code

Finally, share this invitation code with your new member, who will use it at sign-up.

![](/storage/docs/docs/nodem/assets/usage/teams-invite-code.png)

## Signing Up

New team members must sign-up for Nodem using their unique invitation code generated by an owner or admin.

### 1) Click 'Sign Up'

From your Nodem instance's 'Sign In' page, click the '**Sign Up**' text under the username/password form.

![](/storage/docs/docs/nodem/assets/usage/sign-in.png)

### 2) Enter Your Details

Next, you will enter your invitation code and username as provided by your team's owner or a team admin, create a password, and then read and agree to the terms of service.

![](/storage/docs/docs/nodem/assets/usage/sign-up.png)

* **Invitation Code** - unique, one-time-use, and generated by your team's owner or team admin
* **Username** - associated with your invite code and cannot be changed
* **Password**
  * It must contain each of the following:
    * One lowercase character
    * One uppercase character
    * One number
    * One special character
    * 12 characters minimum
  * It may be changed later in your account's settings

When you're ready to proceed, click the '**Sign Up**' button to finish setting up your account.

<x-alert type="success">
You should now be signed-in and on the 'Nodem Manager' dashboard 🎉
</x-alert>

## Removing An Invite

Owner accounts and Team Admins can remove team member invitations directly from the 'Team Management' dashboard.

<x-alert type="warning">
Deleting the invitation code makes it invalid. Generating a new invitation code will be required for the user to join the team.
</x-alert>

### 1) Click 'Remove'

Click the '**Remove**' button next to the pending team member invitation near the top of the 'Team Management' Dashboard.

![](/storage/docs/docs/nodem/assets/usage/teams-invite-remove.png)

### 2) Confirm the Removal

You'll now be presented with the option to cancel or confirm your decision to remove the team member invitation.

If you'd like to proceed with deleting this invitation, click the '**Remove**' button.

![](/storage/docs/docs/nodem/assets/usage/teams-invite-remove-confirm.png)

The pending invitation should no longer be visible from the 'Team Management' dashboard.

## Editing Team Members

Owner accounts and Team Admins can modify the role of a team member directly from the 'Team Management' dashboard. Note that an Owner account cannot be edited.

<x-alert type="info">
Usernames cannot be changed. If a new username is desired, the team member account must be removed, and a new account must be created
</x-alert>

### 1) Click 'Edit'

From the 'Team Management' Dashboard, click the '**Edit**' button next to the desired team member.

![](/storage/docs/docs/nodem/assets/usage/teams-edit-button.png)

### 2) Select a New Role

Next, select a new 'Role' from the dropdown menu, then click the '**Save**' button when you're finished.

![](/storage/docs/docs/nodem/assets/usage/teams-edit-details.png)

You should then see a notification that the member has been updated.

![](/storage/docs/docs/nodem/assets/usage/teams-updated.png)

## Removing Team Members

Owner accounts and Team Admins can remove team members directly from the 'Team Management' dashboard. Note that an Owner account cannot be removed.

### 1) Click 'Remove'

From the 'Team Management' Dashboard, click the '**Remove**' button next to the existing team member you wish to delete.

![](/storage/docs/docs/nodem/assets/usage/teams-remove-button.png)

### 2) Confirm the Removal

You'll now be presented with the option to cancel or confirm your decision to remove the team member invitation.

If you'd like to proceed with deleting this invitation, click the '**Remove**' button.

![](/storage/docs/docs/nodem/assets/usage/teams-remove-confirm.png)

The pending invitation should no longer be visible from the 'Team Management' dashboard.
