## Glossary  <!-- markdownlint-disable MD041 -->

<x-general.sidebar-link path="#2" name="2" />
<x-general.sidebar-link path="#a" name="A" />
<x-general.sidebar-link path="#b" name="B" />
<x-general.sidebar-link path="#c" name="C" />
<x-general.sidebar-link path="#d" name="D" />
<x-general.sidebar-link path="#e" name="E" />
<x-general.sidebar-link path="#f" name="F" />
<x-general.sidebar-link path="#g" name="G" />
<x-general.sidebar-link path="#h" name="H" />
<x-general.sidebar-link path="#i" name="I" />
<x-general.sidebar-link path="#j" name="J" />
<x-general.sidebar-link path="#k" name="K" />
<x-general.sidebar-link path="#l" name="L" />
<x-general.sidebar-link path="#m" name="M" />
<x-general.sidebar-link path="#n" name="N" />
<x-general.sidebar-link path="#o" name="O" />
<x-general.sidebar-link path="#p" name="P" />
<x-general.sidebar-link path="#q" name="Q" />
<x-general.sidebar-link path="#r" name="R" />
<x-general.sidebar-link path="#s" name="S" />
<x-general.sidebar-link path="#t" name="T" />
<x-general.sidebar-link path="#u" name="U" />
<x-general.sidebar-link path="#v" name="V" />
<x-general.sidebar-link path="#w" name="W" />
<x-general.sidebar-link path="#x" name="X" />
<x-general.sidebar-link path="#y" name="Y" />
<x-general.sidebar-link path="#z" name="Z" />
