name: File Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.1.2
        with:
          files: |
            *.md.blade.php

      - name: List all renamed files
        run: |
          for file in "${{ steps.changed-files.outputs.renamed_files }}"; do
            echo "$file was renamed"
          done

      - name: List all deleted files
        run: |
          for file in "${{ steps.changed-files.outputs.deleted_files }}"; do
            echo "$file was deleted"
          done