name: Dependencies

on:
    schedule:
        - cron: "0 0 * * 0"

jobs:
    php:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.GH_TOKEN }}

            - name: Update dependencies
              run: npx @faustbrian/node-composer-check-updates --caret-minor

            - name: Install dependencies
              run: composer update --no-ansi --no-interaction --no-progress --prefer-dist --optimize-autoloader --ignore-platform-reqs

            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v3
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  commit-message: "chore: update PHP dependencies"
                  committer: GitHub <noreply@github.com>
                  author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                  branch: chore/update-php-dependencies
                  delete-branch: true
                  title: "chore: update PHP dependencies"
                  draft: false
    javascript:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.GH_TOKEN }}

            - name: Update dependencies
              run: npx npm-check-updates -u --target minor

            - name: Install dependencies
              run: yarn --ignore-engines

            - name: Rebuild assets
              run: yarn prod

            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v3
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  commit-message: "chore: update JavaScript dependencies"
                  committer: GitHub <noreply@github.com>
                  author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                  branch: chore/update-javascript-dependencies
                  delete-branch: true
                  title: "chore: update JavaScript dependencies"
                  draft: false
